# Generated by Django 5.0.6 on 2024-06-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('address_line_1', models.TextField(max_length=250)),
                ('address_line_2', models.TextField(max_length=250)),
                ('address_line_3', models.TextField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IN', 'India')], default='IN', max_length=50)),
                ('pincode', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
