# Generated by Django 5.0.6 on 2024-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_multipleimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_hobbies', to='accounts.hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_interest', to='accounts.interest'),
        ),
    ]
