# Generated by Django 5.0.6 on 2024-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_hobbies_alter_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(related_name='user_hobbies', to='accounts.hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(related_name='user_interest', to='accounts.interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='multiple_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_images', to='accounts.multipleimages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_reel',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_reels', to='accounts.shortreels'),
        ),
    ]
