# Generated by Django 5.0.6 on 2024-06-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country_user_dob_user_gender_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(choices=[('G', 'Gamming'), ('S', 'Singing'), ('V', 'Video editing')], default='G', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(choices=[('P', 'Programming'), ('R', 'Reading'), ('L', 'Learning tech')], default='P', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='multiple_images',
            field=models.ImageField(blank=True, null=True, upload_to='multiple_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='short_reel',
            field=models.FileField(blank=True, null=True, upload_to='shortreels/'),
        ),
    ]
