# Generated by Django 5.0.6 on 2024-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_hobbies_alter_user_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
