# Generated by Django 5.0.6 on 2024-07-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hobbies_user_interest_user_multiple_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Reading', 'Reading'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Sports', 'Sports'), ('Gardening', 'Gardening'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Photography', 'Photography'), ('Writing', 'Writing'), ('Dancing', 'Dancing')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Literature', 'Literature'), ('Travel', 'Travel'), ('Food', 'Food'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Sports', 'Sports'), ('History', 'History')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserShortReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel', models.FileField(blank=True, null=True, upload_to='short_reels/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='multiple_images',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_reel',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking_habit', models.BooleanField(default=False)),
                ('drinking_habit', models.BooleanField(default=False)),
                ('hobbies', models.ManyToManyField(related_name='user_activities', to='accounts.hobby')),
                ('interest', models.ManyToManyField(related_name='user_activities', to='accounts.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
                ('user_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='accounts.userimages')),
                ('user_qualification', models.ManyToManyField(related_name='user_qualification', to='accounts.userqualifications')),
                ('user_reels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reels', to='accounts.usershortreels')),
            ],
        ),
    ]
