# Generated by Django 5.0.6 on 2024-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_jobseeker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
