# Generated by Django 5.0.6 on 2024-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_interest_name_alter_useractivity_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_images',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_qualification',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_reels',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(choices=[('R', 'Reading'), ('T', 'Traveling'), ('C', 'Cooking'), ('S', 'Sports'), ('G', 'Gardening'), ('Ga', 'Gaming'), ('F', 'Fitness'), ('P', 'Photography'), ('W', 'Writing'), ('D', 'Dancing')], default='R', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(choices=[('T', 'Technology'), ('S', 'Science'), ('L', 'Literature'), ('T', 'Travel'), ('F', 'Food'), ('H', 'Health'), ('Fi', 'Fitness'), ('E', 'Education'), ('Fa', 'Fashion'), ('En', 'Entertainment'), ('Fin', 'Finance'), ('P', 'Politics'), ('Env', 'Environment'), ('Sp', 'Sports'), ('Hi', 'History')], default='T', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='multiple_images',
            field=models.ImageField(blank=True, null=True, upload_to='multiple_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='short_reel',
            field=models.FileField(blank=True, null=True, upload_to='shortreels/'),
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
        migrations.DeleteModel(
            name='UserQualifications',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserShortReels',
        ),
    ]
