# Generated by Django 5.0.6 on 2024-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_useractivity_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinking_habit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_habit',
            field=models.BooleanField(default=False),
        ),
    ]
