# Generated by Django 5.0.6 on 2024-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_drinking_habit_user_smoking_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
