# Generated by Django 5.0.6 on 2024-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('expertise_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(choices=[('H', 'High School'), ('D', 'Diploma'), ('U', 'Undergraduate'), ('G', 'Graduate'), ('P', 'Postgraduate'), ('Ph', 'PhD'), ('O', 'Other')], default='H', max_length=100),
        ),
    ]
