# Generated by Django 5.0.6 on 2024-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobseeker_alter_user_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=100)),
                ('designation', models.CharField(choices=[('IN', 'Intern'), ('JD', 'Junior Developer'), ('SD', 'Senior Developer'), ('TL', 'Team Lead'), ('MG', 'Manager'), ('DR', 'Director'), ('CEO', 'Chief Executive Officer')], default='IN', max_length=100)),
                ('location', models.CharField(choices=[('MUM', 'Mumbai'), ('DEL', 'Delhi'), ('BLR', 'Bangalore'), ('HYD', 'Hyderabad'), ('CHE', 'Chennai'), ('KOL', 'Kolkata'), ('PUN', 'Pune'), ('JAI', 'Jaipur'), ('KOC', 'Kochi'), ('AMD', 'Ahmedabad')], default='KOC', max_length=100)),
            ],
        ),
    ]
