# Generated by Django 5.0.6 on 2024-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('IN', 'India')], default='IN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('R', 'Reading'), ('T', 'Traveling'), ('C', 'Cooking'), ('S', 'Sports'), ('G', 'Gardening'), ('Ga', 'Gaming'), ('F', 'Fitness'), ('P', 'Photography'), ('W', 'Writing'), ('D', 'Dancing')], default='R', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, choices=[('T', 'Technology'), ('S', 'Science'), ('L', 'Literature'), ('T', 'Travel'), ('F', 'Food'), ('H', 'Health'), ('Fi', 'Fitness'), ('E', 'Education'), ('Fa', 'Fashion'), ('En', 'Entertainment'), ('Fin', 'Finance'), ('P', 'Politics'), ('Env', 'Environment'), ('Sp', 'Sports'), ('Hi', 'History')], default='T', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, choices=[('H', 'High School'), ('D', 'Diploma'), ('U', 'Undergraduate'), ('G', 'Graduate'), ('P', 'Postgraduate'), ('Ph', 'PhD'), ('O', 'Other')], default='H', max_length=100, null=True),
        ),
    ]
